---
apiVersion: v1
kind: Service
metadata:
  name: kw
spec:
  selector:
    app: kw
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kw
spec:
  selector:
    matchLabels:
      app: kw
  template:
    metadata:
      labels:
        app: kw
    spec:
      containers:
      - name: kw
        image: kw_php:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        env:
        - name: KW_EMAIL_SUPPORT
          value: kw@kw.local
        - name: MARIADB_DATABASE
          value: ksnadawcza
        - name: MARIADB_USER
          value: ksnadawczy
        - name: MARIADB_PASSWORD
          value: ksnadawczy
        - name: MARIADB_SERVER
          value: mariadb.kw.svc.cluster.local

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kw
  labels:
    name: kw  
spec:
  rules:
  - host: kw.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kw
            port: 
              number: 80

