---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: qqqqwwww
        - name: MARIADB_DATABASE
          value: ksnadawcza
        - name: MARIADB_USER
          value: ksnadawczy
        - name: MARIADB_PASSWORD
          value: ksnadawczy
        - name: MARIADB_INITDB_SKIP_TZINFO
          value: "true"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
      volumes:
        - name: mysql
          hostPath:
            path: /opt/mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
